### ISSUE TITLE
forcats::fct_explicit_na(...)

### ISSUE THREAD

**Issue by spere5** [bioc/GRaNIE#1]
Hi,

I am working with the GRaNIE workflow and got this warning. I am working with R 4.3.2.

Warning message:
There was 1 warning in `dplyr::mutate()`.
i In argument: `peak_gene.distance_class = forcats::fct_explicit_na(...)`.
Caused by warning:
! `fct_explicit_na()` was deprecated in forcats 1.0.0.
i Please use `fct_na_value_to_level()` instead.
i The deprecated feature was likely used in the GRaNIE package.
Please report the issue at <https://git.embl.de/grp-zaugg/GRaNIE/issues>.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of Bioconductor, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
